# Generated by Django 5.1.3 on 2024-11-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_users_avatar_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
